CREATE TABLE
    DOMICILIO (
        CODIGO_DOMICILIO INT PRIMARY KEY NOT NULL,
        CALLE VARCHAR(40) NOT NULL,
        NUMERO INT NOT NULL,
        PISO INT,
        DEPARTAMENTO CHAR(2),
        CODIGO_POSTAL VARCHAR(3100),
        INICIO_DOMICILIO DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL,
        FIN_DOMICILIO DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL,
        PERIOD FOR SYSTEM_TIME (INICIO_DOMICILIO, FIN_DOMICILIO)
    )
WITH
    (SYSTEM_VERSIONING = ON);