-- SQLBook: Code
CREATE TABLE
	EXPEDIENTE (
		NRO_TRAYECTORIA INT NOT NULL PRIMARY KEY CLUSTERED,
		LEGAJO_DOCENTE INT NOT NULL,
		NRO_ESCUELA INT NOT NULL,
		CODIGO_CARGO INT NOT NULL,
		SUPLENTE_TITULAR INT NOT NULL,
		FECHA_INICIO DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL,
		FECHA_HASTA DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL,
		PERIOD FOR SYSTEM_TIME (FECHA_INICIO, FECHA_HASTA),
		FOREIGN KEY (LEGAJO_DOCENTE) REFERENCES DOCENTE (legajo_docente),
		FOREIGN KEY (NRO_ESCUELA) REFERENCES ESCUELA (numero),
		FOREIGN KEY (SUPLENTE_TITULAR) REFERENCES DOCENTE (legajo_docente),
		FOREIGN KEY (CODIGO_CARGO) REFERENCES CARGO (codigo_cargo)
	)
WITH
	(SYSTEM_VERSIONING = ON);