USE [AGMER]
GO

/****** Object:  Table [dbo].[INASISTENCIAS_DOCENTES]    Script Date: 2/6/2023 18:03:09 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[INASISTENCIAS_DOCENTES](
	[DNI_DOCENTE] [int] NOT NULL,
	[CODIGO_INASISTENCIA] [int] NOT NULL,
 CONSTRAINT [PK_INASISTENCIAS_DOCENTES] PRIMARY KEY CLUSTERED 
(
	[DNI_DOCENTE] ASC,
	[CODIGO_INASISTENCIA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[INASISTENCIAS_DOCENTES]  WITH CHECK ADD  CONSTRAINT [FK_INASISTENCIAS_DOCENTES_DOCENTE] FOREIGN KEY([DNI_DOCENTE])
REFERENCES [dbo].[DOCENTE] ([legajo_docente])
GO

ALTER TABLE [dbo].[INASISTENCIAS_DOCENTES] CHECK CONSTRAINT [FK_INASISTENCIAS_DOCENTES_DOCENTE]
GO

ALTER TABLE [dbo].[INASISTENCIAS_DOCENTES]  WITH CHECK ADD  CONSTRAINT [FK_INASISTENCIAS_DOCENTES_INASISTENCIA] FOREIGN KEY([CODIGO_INASISTENCIA])
REFERENCES [dbo].[INASISTENCIA] ([CODIGO_INASISTENCIA])
GO

ALTER TABLE [dbo].[INASISTENCIAS_DOCENTES] CHECK CONSTRAINT [FK_INASISTENCIAS_DOCENTES_INASISTENCIA]
GO


