CREATE TABLE
	LICENCIA (
		CODIGO_LICENCIA INT PRIMARY KEY NOT NULL,
		DNI_DOCENTE INT NOT NULL,
		CODIGO_CONSTANCIA INT NOT NULL,
		TIPO VARCHAR(20),
		INICIO_LICENCIA DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL,
		FIN_LICENCIA DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL,
		PERIOD FOR SYSTEM_TIME (INICIO_LICENCIA, FIN_LICENCIA),
		FOREIGN KEY (DNI_DOCENTE) REFERENCES DOCENTE (LEGAJO_DOCENTE),
		FOREIGN KEY (CODIGO_CONSTANCIA) REFERENCES CONSTANCIA (CODIGO_CONSTANCIA),
	)
WITH
	(SYSTEM_VERSIONING = ON);